### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: ... when add "java" in language array

### ISSUE THREAD

**Issue by amitguptagwl** [highlightjs/highlight.js#1387]
I found that when I don't specify any language or specify "java" in language array then I get following error

```
highlight.pack.js:2 Uncaught SyntaxError: Invalid regular expression: /([Ã€-Ê¸a-zA-Z_$][Ã€-Ê¸a-zA-Z_$0-9]*(<[Ã€-Ê¸a-zA-Z_$][Ã€-Ê¸a-zA-Z_$0-9]*(\s*,\s*[Ã€-Ê¸a-zA-Z_$][Ã€-Ê¸a-zA-Z_$0-9]*)*>)?\s+)+[a-zA-Z_]\w*\s*\(/: Range out of order in character class
    at new RegExp (<anonymous>)
    at t (chrome-extension://ieokebkfhmgbnhlmnijfgcdkbieibipc/quill/modules/highlight/highlight.pack.js:2:1738)
    at r (chrome-extension://ieokebkfhmgbnhlmnijfgcdkbieibipc/quill/modules/highlight/highlight.pack.js:2:2177)
    at chrome-extension://ieokebkfhmgbnhlmnijfgcdkbieibipc/quill/modules/highlight/highlight.pack.js:2:2468
    at Array.forEach (native)
    at r (chrome-extension://ieokebkfhmgbnhlmnijfgcdkbieibipc/quill/modules/highlight/highlight.pack.js:2:2448)
    at s (chrome-extension://ieokebkfhmgbnhlmnijfgcdkbieibipc/quill/modules/highlight/highlight.pack.js:2:2670)
    at l (chrome-extension://ieokebkfhmgbnhlmnijfgcdkbieibipc/quill/modules/highlight/highlight.pack.js:2:4157)
    at chrome-extension://ieokebkfhmgbnhlmnijfgcdkbieibipc/quill/modules/highlight/highlight.pack.js:2:4651
    at Array.forEach (native)
```

**Comment by mcclureski** [comment]
a friends getting the same issue, when theres no specified coding language it gives errors

**Comment by amitguptagwl** [comment]
I'm not sure when this issue was closed. But this is not quilljs issue. I have experienced in higlight js only in other projects too.

**Comment by ee-** [comment]
I'm encountering similar problem.
`highlight.pack.js:2 Uncaught SyntaxError: Invalid regular expression: /([Ã€-Ê¸a-zA-Z_$][Ã€-Ê¸a-zA-Z_$0-9]*(<[Ã€-Ê¸a-zA-Z_$][Ã€-Ê¸a-zA-Z_$0-9]*(\s*,\s*[Ã€-Ê¸a-zA-Z_$][Ã€-Ê¸a-zA-Z_$0-9]*)*>)?\s+)+[a-zA-Z_]\w*\s*\(/: Range out of order in character class`

highlight.js is somehow unable to auto detect languages if "other" languages were selected.

**Comment by falstack** [comment]
i have same issue

**Comment by jprogramer** [comment]
same here...(I was so excited to start using hljs but now I have to drop it T_T)

**Comment by jprogramer** [comment]
guys just change java id regex...
someone need to fix the bug at https://github.com/isagalaev/highlight.js/blob/master/src/languages/java.js (line: 8) until then you can just search for: 'hljs.registerLanguage("java"' in your highlight.pack.js then change:
`hljs.registerLanguage("java",function(e){var a="**[\u00C0-\u02B8a-zA-Z_$][\u00C0-\u02B8a-zA-Z_$0-9]***"`
to anything that suite your needs, for me I don't need UTF-8 chars so I m using a simple regex:
`hljs.registerLanguage("java",function(e){var a="**[a-zA-Z_$][a-zA-Z_$0-9]***"`
(I hope that I didn't just broke the copyright of this api >_<)

**Comment by AlphaJuliettOmega** [comment]
What the heck, I just stumbled upon this today. Still figuring out how to fix it

**Comment by evbarnett** [comment]
Can confirm this bug is still active

**Comment by egor-rogov** [comment]
Hi everybody,
what browser do you use (exact version) when encounter this bug?
@amitguptagwl @mcclureski @ee- @falstack @jprogramer @AlphaJuliettOmega @evbarnett

**Comment by falstack** [comment]
chrome，forgot version，not old

**Comment by mikelmcdaniel** [comment]
> Hi everybody,
> what browser do you use (exact version) when encounter this bug?
> @amitguptagwl @mcclureski @ee- @falstack @jprogramer @AlphaJuliettOmega @evbarnett

Using highlight.js/9.12.0/highlight.min.js

Google Chrome | 69.0.3497.100 (Official Build) (64-bit)
-- | --
Revision | 8920e690dd011895672947112477d10d5c8afb09-refs/branch-heads/3497@{#948}
OS | Linux
JavaScript | V8 6.9.427.23
Flash | 31.0.0.122 /home/mikel/.config/google-chrome/PepperFlash/31.0.0.122/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Command Line | /usr/bin/google-chrome --incognito --flag-switches-begin --flag-switches-end
Executable Path | /opt/google/chrome/google-chrome
Profile Path | /home/mikel/.config/google-chrome/Default
Variations | c134752e-1ece35533e006338-3f4a17df1a0d11d4-2f9febdfe202a358-ca7d8d80ebeb14fc-3f4a17df752a9400-3d47f4f4b7e2524c-ca7d8d808fe39baa-3f4a17df241fff6c-ca7d8d808502ae4f-e1031ab53095aa95-3f4a17df7c1bc906-f55a797447e5d3db-3d47f4f49ca1387e-a3a148311149accc-5c9438774dc30737-b8a5ea08c865fdc1-ca7d8d80a582a1b8-ad75ce178ee5ed19-ca7d8d8074658432-ca7d8d80ebbb4e0a-ca7d8d80267255c3-f4950e99249dd49a-86f8c66a88a387d2-ee748cef8f1e27f-ca7d8d80edbcf7c5-1cc1312c43f62d3b-28165b593a0563a1-65222f0b9e5c75f1-b03cf0e96872f671-991e1e1f79cb77b-3f4a17df2ca9c26b-3f4a17df4ea303a6-ecbb250e6e6e0c7e-3f17a7d8d92562a9-4d2fac874da5ae82-91c810ef2c1d398c-3f4a17df6973a1cf-3f4a17dfcc54eb06-28165b5958a025e3-36e97b2cdf072bba-ca7d8d80ff29b1bd-37ef7e174bc337ce-69465896ddf77e2c-ca7d8d801354da85-f1a864dc17507c76-3d47f4f4494d8760-52325d433ac60855-486e2a9cf296190c-75cb33fc4442aae2-e1cc0f14ed1d377-e1cc0f1475f0f0a0-d7f6b13ce2b18481-9d9eea77e7e71889-e1cc0f143a8271ac-12c226b1ceb06f-d13723343a4029d-ca7d8d806ab94979-3f4a17df41aa6aaa-da82a76f94e68624-803f8fc48834fcca-cf4f6ead81c6897f-3d47f4f4ea0f933d-ca7d8d80

Exact error:
Uncaught SyntaxError: Invalid regular expression: /([Ã€-Ê¸a-zA-Z_$][Ã€-Ê¸a-zA-Z_$0-9]*(<[Ã€-Ê¸a-zA-Z_$][Ã€-Ê¸a-zA-Z_$0-9]*(\s*,\s*[Ã€-Ê¸a-zA-Z_$][Ã€-Ê¸a-zA-Z_$0-9]*)*>)?\s+)+[a-zA-Z_]\w*\s*\(/: Range out of order in character class
    at new RegExp (<anonymous>)
    at r (highlight.min.js:2)
    at a (highlight.min.js:2)
    at highlight.min.js:2
    at Array.forEach (<anonymous>)
    at a (highlight.min.js:2)
    at u (highlight.min.js:2)
    at d (highlight.min.js:2)
    at f (highlight.min.js:2)
    at NodeList.forEach (<anonymous>)

**Comment by craigsdennis** [comment]
Not sure if it helps but:

This build at cdnjs seems to have the problem:
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>

And not this one:
<script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.13.1/build/highlight.min.js"></script>


Wondering if it's a hosting encoding problem. ¯\_(ツ)_/¯

**Comment by nchambers** [comment]
This appears to be a character encoding problem with the browser that is loading your page. It is not using UTF-8 by default. I was able to fix it by making sure I had UTF-8 in the meta tag of the HTML page that is using highlightjs:
    <meta charset="utf-8">

Add that to your document's <head> and see if that solves it for you.

**Comment by marcoscaceres** [comment]
You can also do:

```
<script
 charset="UTF-8"
 href="...">
```

to overcome the encoding issue.

**Comment by yyyc514** [comment]
> This build at cdnjs seems to have the problem:
> And not this one:

@craigsdennis 

Can you reconfirm?  I tried just now to fetch the files from both and they both are sporting the proper Content-Type headers... I was expecting to see some difference.

**Comment by yyyc514** [comment]
Can anyone confirm they are still having issues with this?

**Comment by yyyc514** [comment]
Closing as old/stale issue with no recent activity or responses.   If anyone is actually still having issues with this please let us know and we can reopen.
