### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by sebhewelt** [highlightjs/highlight.js#1628]
Hey,

I'm trying to use hl with javascript. 
I have preCodes nodelist which contains code blocks (i don't add anything dynamically).

```
  componentDidMount() {
   // logs an error to the console i posted below
   let preCodes = Array.from(document.querySelectorAll('pre code:not(.hljs)'));
    console.log(preCodes); // logs nodes array with code blocks
    preCodes.forEach(function(i, block) {
      hljs.highlightBlock(block);
    });
  }
```

Console:
```
Uncaught TypeError: Cannot read property 'replace' of undefined
    at t (highlight.pack.min.js:2)
    at m (highlight.pack.min.js:2)
    at Object.g [as highlightBlock] (highlight.pack.min.js:2)
    at post.js:18
    at Array.map (<anonymous>)
    at PostTemplate.componentDidMount (post.js:17)
    at PostTemplate.proxiedComponentDidMount [as componentDidMount] (createPrototypeProxy.js:66)
    at ReactCompositeComponent.js:262
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponent.js:261
```

I've seen somewhat similar problem [here](https://github.com/isagalaev/highlight.js/issues/933), but the code blocks there were added dynamically using AJAX, which i don't do.

Help appreciated. :)

**Comment by stevenhair** [comment]
I'm experiencing the same thing with Node.js:

```javascript
hljs.highlightBlock('<pre><code class="python language-python">print("foo")</code></pre>')
```

results in

```
TypeError: Cannot read property 'replace' of undefined
    at escape (/home/steve/dev/blog-api/node_modules/highlight.js/lib/highlight.js:58:18)
    at highlightAuto (/home/steve/dev/blog-api/node_modules/highlight.js/lib/highlight.js:557:14)
    at Object.highlightBlock (/home/steve/dev/blog-api/node_modules/highlight.js/lib/highlight.js:630:59)
    at eval (eval at <anonymous> (/home/steve/dev/blog-api/src/posts/markdown-to-html.js:19:13), <anonymous>:1:6)
    at Node.<anonymous> (/home/steve/dev/blog-api/src/posts/markdown-to-html.js:19:13)
    at initialize.exports.each (/home/steve/dev/blog-api/node_modules/cheerio/lib/api/traversing.js:300:24)
    at MarkdownToHtml.styleCodeBlocks (/home/steve/dev/blog-api/src/posts/markdown-to-html.js:18:18)
    at MarkdownToHtml.convert (/home/steve/dev/blog-api/src/posts/markdown-to-html.js:12:21)
    at Context.it (/home/steve/dev/blog-api/tests/posts/markdown-to-html.test.js:30:35)
    at callFn (/home/steve/dev/blog-api/node_modules/mocha/lib/runnable.js:354:21)
    at Test.Runnable.run (/home/steve/dev/blog-api/node_modules/mocha/lib/runnable.js:346:7)
    at Runner.runTest (/home/steve/dev/blog-api/node_modules/mocha/lib/runner.js:442:10)
    at /home/steve/dev/blog-api/node_modules/mocha/lib/runner.js:560:12
    at next (/home/steve/dev/blog-api/node_modules/mocha/lib/runner.js:356:14)
    at /home/steve/dev/blog-api/node_modules/mocha/lib/runner.js:366:7
    at next (/home/steve/dev/blog-api/node_modules/mocha/lib/runner.js:290:14)
    at Immediate._onImmediate (/home/steve/dev/blog-api/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
```

**Comment by SunboX** [comment]
Maybe highlight.js somehow relies on jQuery?

**Comment by asionius** [comment]
The type of `document.querySelectorAll` is `HttpCollection`.  The `Array.from` method change it to Array removing some properties which prevent the block from being highlighted.
My solution is use operator `[]` with number index.
For example:
```
      let preCodes = document.querySelectorAll("pre code:not(.hljs)");
      for(var i = 0; i < preCodes.length; i++)
          hljs.highlightBlock(preCodes[i]);
```
and it worked! :)

**Comment by yyyc514** [comment]
Looks like this is resolved.  Closing.
