### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by chenglou** [highlightjs/highlight.js#1833]
Hello! I just freshly cloned this repo and did `yarn && yarn test`. Here's the error:

```
❯ node -v
v10.6.0

❯ yarn test
yarn run v1.3.2
$ mocha --globals document test
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../../build'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by chenglou** [comment]
Yeah tried with `npm install && npm test` too. Is my node version not right?

**Comment by marcoscaceres** [comment]
Version is right... strange :/

**Comment by marcoscaceres** [comment]
Oh, I forgot! you need to build before you test.. for example:

```
node tools/build.js :common
```

There is a little more info here:
https://highlightjs.readthedocs.io/en/latest/building-testing.html

**Comment by benswift** [comment]
Hey there,

I'm still having this problem - following the steps on [readthedocs](https://highlightjs.readthedocs.io/en/latest/building-testing.html) doesn't seem to fix things. To wit:

```
bash-3.2$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65

bash-3.2$ node -v
v10.11.0

bash-3.2$ git show-ref HEAD
dfe7bac4efcb1e873f12d62aac3f608f7490ff00 refs/remotes/origin/HEAD

cd highlight.js/

bash-3.2$ npm install
added 241 packages from 707 contributors and audited 391 packages in 3.062s
found 22 vulnerabilities (5 low, 10 moderate, 7 high)
  run `npm audit fix` to fix them, or `npm audit` for details

bash-3.2$ node tools/build.js :common
Starting build.
Copying documentation.
Writing documentation.
Generating demo.
Building highlight.js pack file.
Compressing highlight.js pack file.
Writing highlight.js pack file.
Finished build.

bash-3.2$ npm test

> highlight.js@9.12.0 test /Users/ben/Desktop/highlight.js
> mocha --globals document test

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../../build'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/ben/Desktop/highlight.js/test/api/ident.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Suite.<anonymous> (/Users/ben/Desktop/highlight.js/test/api/index.js:4:3)
    at Object.create (/Users/ben/Desktop/highlight.js/node_modules/mocha/lib/interfaces/common.js:112:19)
    at context.describe.context.context (/Users/ben/Desktop/highlight.js/node_modules/mocha/lib/interfaces/bdd.js:40:27)
    at Object.<anonymous> (/Users/ben/Desktop/highlight.js/test/api/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/ben/Desktop/highlight.js/test/index.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/ben/Desktop/highlight.js/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/ben/Desktop/highlight.js/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/ben/Desktop/highlight.js/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/ben/Desktop/highlight.js/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
npm ERR! Test failed.  See above for more details.
```

Sorry about the dump - hopefully it's got all the relevant info. I can confirm that after the `npm test` step there is a `build/` directory created which contains a `highlight.pack.js`.

**Comment by marcoscaceres** [comment]
Hey @benswift,  seems you are missing the `-t` option (it defaults to `browser`, which is why it's failing.) 

Try:
```
node ./tools/build.js :common
npm run test-browser
```

Alternatively, try with `-t node` (target):
```
node tools/build.js -t node :common
npm test
```

**Comment by benswift** [comment]
Oh, that's better. Thanks so much - sorry about the issue spam.
