### ISSUE TITLE
TypeError: Cannot read property 'length' of null.

### ISSUE THREAD

**Issue by rama291041610** [highlightjs/highlight.js#2072]
## For Bug
This library is used in [hexo](https://github.com/hexojs/hexo). When I execute `hexo s`, sometimes it throws a error:  
```
PS>hexo s
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'length' of null
    at subMode (E:\software\blog\hexo\node_modules\highlight.js\lib\highlight.js:388:42)
    at processLexeme (E:\software\blog\hexo\node_modules\highlight.js\lib\highlight.js:497:22)
    at highlight (E:\software\blog\hexo\node_modules\highlight.js\lib\highlight.js:581:17)
    at E:\software\blog\hexo\node_modules\highlight.js\lib\highlight.js:627:21
    at Array.forEach (<anonymous>)
    at Object.highlightAuto (E:\software\blog\hexo\node_modules\highlight.js\lib\highlight.js:626:62)
    at E:\software\blog\hexo\node_modules\hexo-util\lib\highlight.js:117:25
    at highlight (E:\software\blog\hexo\node_modules\hexo-util\lib\highlight.js:120:7)
    at highlightUtil (E:\software\blog\hexo\node_modules\hexo-util\lib\highlight.js:22:14)
    at data.content.data.content.replace (E:\software\blog\hexo\node_modules\hexo\lib\plugins\filter\before_post_render\backtick_code_block.js:59:15)
    at String.replace (<anonymous>)
    at Hexo.backtickCodeBlock (E:\software\blog\hexo\node_modules\hexo\lib\plugins\filter\before_post_render\backtick_code_block.js:14:31)
    at Hexo.tryCatcher (E:\software\blog\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\software\blog\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.each.filter (E:\software\blog\hexo\node_modules\hexo\lib\extend\filter.js:63:65)
    at tryCatcher (E:\software\blog\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (E:\software\blog\hexo\node_modules\bluebird\js\release\reduce.js:155:18)
    at Object.gotAccum (E:\software\blog\hexo\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (E:\software\blog\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\software\blog\hexo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\software\blog\hexo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromiseCtx (E:\software\blog\hexo\node_modules\bluebird\js\release\promise.js:606:10)
```
## For Question

It seems that some variable is null. How can fix this bug?

**Comment by yyyc514** [comment]
If you can provide an isolated reproducible test case that we can use to reproduce the problem that would be great.

**Comment by yyyc514** [comment]
If you were using this to build your blog, shouldn't it "always" throw an error vs only "sometimes"?  IE, if you reset your build cache (or whatever) and then said "build my whole blog"... wouldn't it always blow up when it hit the invalid snippet of code?

And then if you could track it down to a reproducible single piece of code, then we'd be 80% there. :-)

**Comment by yyyc514** [comment]
Have you seen this issue since July?

**Comment by yyyc514** [comment]
Without any other reports since July and no confirmation from user that this is still an open issue will consider fixed.

--- 

Closing due to inactivity (we're cleaning out old stale issues that have likely been fixed).  If this is still a current reproducible issue please respond and we will happily re-open.

**Comment by gritFJH** [comment]
I also encountered this problem when I tried to add the following code snippet to the article:
```
[root@first-test src]# python main.py 
  0%|          | 0/1723811 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 148, in <module>
    disposeData(data, mysql_conn, doList=list_to_new_table)
  File "main.py", line 77, in disposeData
    conn.executeInsterSQL(mongodb_collection, key_arr, pla_arr, val_arr)
  File "/root/src/DBUtils.py", line 109, in executeInsterSQL
    cursor.execute(sql, val_arr)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.DataError: (1406, "Data too long for column 'response' at row 1")
  0%|          | 0/1723811 [00:00<?, ?it/s]
```
I guess there are special characters in the code block that caused this error.

**Comment by yyyc514** [comment]
@gritFJH Can you make a JSFiddle or otherwise reproducible example of the problem in action?

You can fork my example:
https://jsfiddle.net/ajoshguy/a1kntyg4/
