### ISSUE TITLE
Security: bump npm dependencies on `handlebars`

### ISSUE THREAD

**Issue by jf990** [highlightjs/highlight.js#2143]
I can no longer install dependencies:

```bash
$ npm i
npm ERR! path Projects/highlight.js/node_modules/gear-lib/node_modules/gear
npm ERR! code EISGIT
npm ERR! git Projects/highlight.js/node_modules/gear-lib/node_modules/gear: Appears to be a git repo or submodule.
npm ERR! git     Projects/highlight.js/node_modules/gear-lib/node_modules/gear
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

Both `gear` and `gear-lib` have `.git` folders inside them. It looks like you can get around this issue by rming the .git folders out of gear and gear-lib, but then you have to do this every time.

**Comment by yyyc514** [comment]
They have git folders that npm put there? Or did you check all these things out of GitHub manually?  I haven't run into this so I'l a little in the dark.

**Comment by yyyc514** [comment]
No issue here:

```
% git clone git@github.com:highlightjs/highlight.js.git            2.6.5
Cloning into 'highlight.js'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 31660 (delta 11), reused 12 (delta 2), pack-reused 31627
Receiving objects: 100% (31660/31660), 9.02 MiB | 9.23 MiB/s, done.
Resolving deltas: 100% (20528/20528), done.
~/w/tmp % cd highlight.js/                                                 2.6.5
~/w/t/highlight.js(master✔) % npm i                                        2.6.5
added 469 packages from 863 contributors and audited 2643 packages in 5.854s
found 3 vulnerabilities (1 low, 1 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

Please provide fulls steps to reproduce (where you are getting source from, etc).

**Comment by yyyc514** [comment]
Ping.

**Comment by jf990** [comment]
I did a pull to update to the latest and a clean npm install and the issue i reported above no longer happens. However:

1. `npm test` now fails on `audrino`

2. `npm audit` shows a critical and high level issue with `handlbars` and I tried to see if I could fix it but then the .git error appears:

```bash
$ npm audit
found 3 vulnerabilities (1 low, 1 high, 1 critical) in 2643 scanned packages
  3 vulnerabilities require manual review. See the full report for details.
$ npm audit fix
npm ERR! path Projects/highlight.js/node_modules/gear
npm ERR! code EISGIT
npm ERR! git Projects/highlight.js/node_modules/gear: Appears to be a git repo or submodule.
npm ERR! git     /Projects/highlight.js/node_modules/gear
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

it looks like updating handlebars to a later version will address the 2 audit issues.

**Comment by yyyc514** [comment]
> npm test now fails on arduino

Can you show the results of the run?  We can't even commit code here if all the tests don't pass, so tests failing is kind of unusual.

**Comment by jf990** [comment]
this is what I see

```

  arduino
    1) should markup default


  434 passing (7s)
  1 failing

  1) arduino
       should markup default:

      AssertionError: expected '<span class="hljs-comment">/*\n  Blink\n  Turns on an LED on for one second, then off for one second, repeatedly.\n\n  This example code is in the public domain.\n */</span>\n\n<span class="hljs-comment">// Pin 13 has an LED connected on most Arduino boards.</span>\n<span class="hljs-comment">// give it a name:</span>\n<span class="hljs-keyword">int</span> led = <span class="hljs-number">13</span>;\n\n<span class="hljs-comment">// the setup routine runs once when you press reset:</span>\n<span class="hljs-keyword">void</span> <span class="hljs-built_in">setup</span>() {\n  <span class="hljs-comment">// initialize the digital pin as an output.</span>\n  <span class="hljs-built_in">pinMode</span>(led, <span class="hljs-literal">OUTPUT</span>);\n}\n\n<span class="hljs-comment">// the loop routine runs over and over again forever:</span>\n<span class="hljs-keyword">void</span> <span class="hljs-built_in">loop</span>() {\n  <span class="hljs-built_in">digitalWrite</span>(led, <span class="hljs-literal">HIGH</span>);   <span class="hljs-comment">// turn the LED on (HIGH is the voltage level)</span>\n  <span class="hljs-built_in">delay</span>(<span class="hljs-number">1000</span>);               <span class="hljs-comment">// wait for a second</span>\n  <span class="hljs-built_in">digitalWrite</span>(led, <span class="hljs-literal">LOW</span>);    <span class="hljs-comment">// turn the LED off by making the voltage LOW</span>\n  <span class="hljs-built_in">delay</span>(<span class="hljs-number">1000</span>);               <span class="hljs-comment">// wait for a second</span>\n}' to be '<span class="hljs-comment">/*\n  Blink\n  Turns on an LED on for one second, then off for one second, repeatedly.\n\n  This example code is in the public domain.\n */</span>\n\n<span class="hljs-comment">// Pin 13 has an LED connected on most Arduino boards.</span>\n<span class="hljs-comment">// give it a name:</span>\n<span class="hljs-keyword">int</span> led = <span class="hljs-number">13</span>;\n\n<span class="hljs-comment">// the setup routine runs once when you press reset:</span>\n<span class="hljs-function"><span class="hljs-keyword">void</span> <span class="hljs-title">setup</span><span class="hljs-params">()</span> </span>{\n  <span class="hljs-comment">// initialize the digital pin as an output.</span>\n  <span class="hljs-built_in">pinMode</span>(led, <span class="hljs-literal">OUTPUT</span>);\n}\n\n<span class="hljs-comment">// the loop routine runs over and over again forever:</span>\n<span class="hljs-function"><span class="hljs-keyword">void</span> <span class="hljs-title">loop</span><span class="hljs-params">()</span> </span>{\n  <span class="hljs-built_in">digitalWrite</span>(led, <span class="hljs-literal">HIGH</span>);   <span class="hljs-comment">// turn the LED on (HIGH is the voltage level)</span>\n  <span class="hljs-built_in">delay</span>(<span class="hljs-number">1000</span>);               <span class="hljs-comment">// wait for a second</span>\n  <span class="hljs-built_in">digitalWrite</span>(led, <span class="hljs-literal">LOW</span>);    <span class="hljs-comment">// turn the LED off by making the voltage LOW</span>\n  <span class="hljs-built_in">delay</span>(<span class="hljs-number">1000</span>);               <span class="hljs-comment">// wait for a second</span>\n}'      
      actual expected
      
       1 | <span class="hljs-comment">/*
       2 |   Blink
       3 |   Turns on an LED on for one second, then off for one second, repeatedly.
       4 | 
       5 |   This example code is in the public domain.
       6 |  */</span>
       7 | 
       8 | <span class="hljs-comment">// Pin 13 has an LED connected on most Arduino boards.</span>
       9 | <span class="hljs-comment">// give it a name:</span>
      10 | <span class="hljs-keyword">int</span> led = <span class="hljs-number">13</span>;
      11 | 
      12 | <span class="hljs-comment">// the setup routine runs once when you press reset:</span>
      13 | <span class="hljs-function"><span class="hljs-keyword">void</span> <span class="hljs-built_intitle">setup</span>()><span {class="hljs-params">()</span> </span>{
      14 |   <span class="hljs-comment">// initialize the digital pin as an output.</span>
      15 |   <span class="hljs-built_in">pinMode</span>(led, <span class="hljs-literal">OUTPUT</span>);
      16 | }
      17 | 
      18 | <span class="hljs-comment">// the loop routine runs over and over again forever:</span>
      19 | <span class="hljs-function"><span class="hljs-keyword">void</span> <span class="hljs-built_intitle">loop</span>()><span {class="hljs-params">()</span> </span>{
      20 |   <span class="hljs-built_in">digitalWrite</span>(led, <span class="hljs-literal">HIGH</span>);   <span class="hljs-comment">// turn the LED on (HIGH is the voltage level)</span>
      21 |   <span class="hljs-built_in">delay</span>(<span class="hljs-number">1000</span>);               <span class="hljs-comment">// wait for a second</span>
      22 |   <span class="hljs-built_in">digitalWrite</span>(led, <span class="hljs-literal">LOW</span>);    <span class="hljs-comment">// turn the LED off by making the voltage LOW</span>
      23 |   <span class="hljs-built_in">delay</span>(<span class="hljs-number">1000</span>);               <span class="hljs-comment">// wait for a second</span>
      24 | }
      
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at Projects/highlight.js/test/markup/index.js:27:32
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Holder$2._callFunction (eval at generateHolderClass (node_modules/bluebird/js/release/join.js:92:16), <anonymous>:14:44)
      at Holder$2.checkFulfillment (eval at generateHolderClass (node_modules/bluebird/js/release/join.js:92:16), <anonymous>:29:30)
      at Promise.eval (eval at thenCallback (node_modules/bluebird/js/release/join.js:14:16), <anonymous>:6:20)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:571:21)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:619:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:699:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:643:18)
      at Projects/highlight.js/node_modules/bluebird/js/release/nodeback.js:42:21
      at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)

npm ERR! Test failed.  See above for more details.
```

**Comment by jf990** [comment]
@yyyc514 not sure what the issue is, could be a linux vs. windows line ending with the test data file, or maybe the line numbers? I'm running on macOS.

**Comment by yyyc514** [comment]
Are you building first?

```
node tools/build.js -t node
```

MacOS here also.  Just test master, no issues.

**Comment by yyyc514** [comment]
```
% md5 test/markup/arduino/default.*                                                                                                                                              2.6.5
MD5 (test/markup/arduino/default.expect.txt) = 2041e411ab6c9b8f7b8a8c1fae1d9787
MD5 (test/markup/arduino/default.txt) = a9072d99ce6aad503235398b48259ed2
```

**Comment by jf990** [comment]
@yyyc514 crap, sorry, yes, build fixed it.
