### ISSUE TITLE
The testing suite does not run (on Windows)

### ISSUE THREAD

**Issue by schtandard** [highlightjs/highlight.js#2742]
**How to reproduce:**
- Install `node.js`.
- From `highlight.js`' root directory, run `npm install`, then `npm test`.
- The following messages appear:
```
> highlight.js@10.2.1 test D:\Projekte\highlight.js_parser\highlight.js
> mocha test


Error: Cannot find module '../build'
Require stack:
- D:\Projekte\highlight.js_parser\highlight.js\test\index.js
- D:\Projekte\highlight.js_parser\highlight.js\node_modules\mocha\lib\esm-utils.js
- D:\Projekte\highlight.js_parser\highlight.js\node_modules\mocha\lib\mocha.js
- D:\Projekte\highlight.js_parser\highlight.js\node_modules\mocha\lib\cli\one-and-dones.js
- D:\Projekte\highlight.js_parser\highlight.js\node_modules\mocha\lib\cli\options.js
- D:\Projekte\highlight.js_parser\highlight.js\node_modules\mocha\bin\mocha
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\Projekte\highlight.js_parser\highlight.js\test\index.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.exports.requireOrImport (D:\Projekte\highlight.js_parser\highlight.js\node_modules\mocha\lib\esm-utils.js:20:12)
    at Object.exports.loadFilesAsync (D:\Projekte\highlight.js_parser\highlight.js\node_modules\mocha\lib\esm-utils.js:33:34)
    at Mocha.loadFilesAsync (D:\Projekte\highlight.js_parser\highlight.js\node_modules\mocha\lib\mocha.js:427:19)
    at singleRun (D:\Projekte\highlight.js_parser\highlight.js\node_modules\mocha\lib\cli\run-helpers.js:156:15)
    at exports.runMocha (D:\Projekte\highlight.js_parser\highlight.js\node_modules\mocha\lib\cli\run-helpers.js:225:10)
    at Object.exports.handler (D:\Projekte\highlight.js_parser\highlight.js\node_modules\mocha\lib\cli\run.js:366:11)
    at D:\Projekte\highlight.js_parser\highlight.js\node_modules\yargs\lib\command.js:241:49
npm ERR! Test failed.  See above for more details.
```

---

#2725 makes me think that this may also have something to do with the fact that I am on Windows (10).
I am running `node` version `v12.18.4` and `npm` version `6.14.6`.

**Comment by allejo** [comment]
Tests run fine for me on Windows.

> Error: Cannot find module '../build'

This means you don't have a build locally. You're going to want to do `npm run build_and_test` instead of just `npm test`.

**Comment by schtandard** [comment]
Ah, thanks for the clarification. I guess I didn't give the word "build" in [the manual][test-doc] enough wait.

Though the phrasing there
> You can use the node build to run the tests in the command line with `npm test` after installing the dependencies with `npm install`.

does make it sound like I want to run `npm test` right after `npm install`. May be worth a clarification.

[test-doc]: https://highlightjs.readthedocs.io/en/latest/building-testing.html#basic-testing

**Comment by joshgoebel** [comment]
@schtandard If you can think of a nice way to clarify doc PR please. :)
