### ISSUE TITLE
.d.ts incompatible with NLS

### ISSUE THREAD

**Issue by PeterWone** [highlightjs/highlight.js#3732]
**Describe the issue/behavior that seems buggy**

Typescript .d.ts not compatible with NLS

(node language services, it's for localisation)

**Sample Code or Instructions to Reproduce**
Get the VS Code sample extension for NLS and add highlight.js to its deps, then do a gulp build.

[16:07:24] Using gulpfile C:\projects\vsc-print\gulpfile.js
[16:07:24] Starting 'build'...
[16:07:24] Starting 'cleanTask'...
[16:07:24] Finished 'cleanTask' after 8.8 ms
[16:07:24] Starting 'internalNlsCompileTask'...
C:/projects/vsc-print/node_modules/highlight.js/types/index.d.ts(55,54): error TS1256: A rest element must be last in a tuple type.
TypeScript: 1 semantic error
TypeScript: emit succeeded (with errors)
[16:07:26] 'internalNlsCompileTask' errored after 2.39 s
[16:07:26] Error: TypeScript: Compilation failed
    at Output.mightFinish (C:\projects\vsc-print\node_modules\gulp-typescript\release\output.js:130:43)
    at C:\projects\vsc-print\node_modules\gulp-typescript\release\output.js:43:22
[16:07:26] 'build' errored after 2.4 s

**Comment by joshgoebel** [comment]
Closing as dup of #3703.

**Comment by PeterWone** [comment]
Fair enough. I searched for NLS but I do believe you're right, it's the same issue.
