### ISSUE TITLE
error i got and dont know

### ISSUE THREAD

**Issue by victormbii** [highlightjs/highlight.js#4175]
SyntaxError: Invalid regular expression: /^/_next/data/development/{root).json$/: Unmatched ')'
    at new RegExp (<anonymous>)
    at buildDataRoute (node_modules\next\src\server\lib\router-utils\build-data-route.ts:32:6)
    at page (node_modules\next\src\server\lib\router-utils\setup-dev-bundler.ts:834:39)

**Additional context**

**Comment by joshgoebel** [comment]
Nothing in the error you posted that looks like it has anything to do with Highlight.js at all.
